### ISSUE TITLE
Wiki: Monitoring Cassandra – Grafana credentials

### ISSUE THREAD

**Issue by m99coder** [k8ssandra/workshop#1]
First things first: Thanks for this great workshop.

While trying to take these steps one by one, I stumbled upon an issue being unable to login into Grafana. It turned out that the default password is `admin` (instead of `secret`) and has to be changed after the first successful login (ideally to `secret` then, I guess).

Reference: https://github.com/k8ssandra/workshop/wiki/Monitoring-Cassandra

**Comment by jeffreyscarpenter** [comment]
Odd, I had recently changed this exercise to match what is on the getting started instructions page for SREs on the K8ssandra website: https://docs.k8ssandra.io/quickstarts/site-reliability-engineer/.  

In any case, you can obtain the password like this:

`helm show values k8ssandra/k8ssandra | grep "adminPassword"`

**Comment by m99coder** [comment]
The `helm` command returned `secret` as well. There is a mismatch to this line, I guess: https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/values.yaml#L699.
