### ISSUE TITLE
[HW] Sarvajit Sankar

### ISSUE THREAD

**Issue by KINGSLAYER99** [k8ssandra/workshop#2]
**Name:** Sarvajit Sankar
**Linkedin Profile:** https://www.linkedin.com/in/sarvajit-s-55620429/

Attach the homework screenshots below:
-----------------------------------------
![Screenshot from 2021-05-04 22-28-49](https://user-images.githubusercontent.com/34660862/117041842-e360c880-ad28-11eb-8dde-7f29ad40798c.png)
![Screenshot from 2021-05-04 22-28-55](https://user-images.githubusercontent.com/34660862/117041845-e491f580-ad28-11eb-8d5f-7b852d79cf0e.png)
![Screenshot from 2021-05-04 22-29-10](https://user-images.githubusercontent.com/34660862/117041847-e52a8c00-ad28-11eb-9145-6687f7f30058.png)
![Screenshot from 2021-05-04 22-29-13](https://user-images.githubusercontent.com/34660862/117041849-e5c32280-ad28-11eb-97a1-899acb50ff7c.png)
![Screenshot from 2021-05-04 22-29-15](https://user-images.githubusercontent.com/34660862/117041851-e6f44f80-ad28-11eb-943b-4f6531bca511.png)
![Screenshot from 2021-05-04 22-29-16](https://user-images.githubusercontent.com/34660862/117041857-e78ce600-ad28-11eb-9f31-2acce1699b58.png)
![Screenshot from 2021-05-04 22-29-19](https://user-images.githubusercontent.com/34660862/117041858-e8257c80-ad28-11eb-92b1-28900e69d801.png)
![Screenshot from 2021-05-04 22-30-25](https://user-images.githubusercontent.com/34660862/117041863-e956a980-ad28-11eb-940e-c056d5e7d9af.png)
![Screenshot from 2021-05-04 22-33-41](https://user-images.githubusercontent.com/34660862/117041866-e9ef4000-ad28-11eb-86f3-6a818b2660ce.png)

**Comment by HadesArchitect** [comment]
Great job! Sorry for the delay!

**Comment by KINGSLAYER99** [comment]
@HadesArchitect, I am curious to know, by when will we get public badge for the workshop?

**Comment by HadesArchitect** [comment]
@KINGSLAYER99 Right now! https://api.badgr.io/public/assertions/ji1z9uiWQW6mydymGHC8vA?identity__url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fsarvajit-s-55620429%2F Congrats again!

**Comment by KINGSLAYER99** [comment]
Thank you so much @HadesArchitect
