### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by nordwars** [k8ssandra/workshop#4]
**Name:** Glenn Sinclair
**Linkedin Profile:** https://www.linkedin.com/in/glenn-sinclair-1b0aa33/

Attach the homework screenshots below:
-----------------------------------------

Sorry, I wasn't aware that we were supposed to be taking screenshots at the time we were going through the steps, so I am missing some from the earlier sections. But here are some shots from the later sections that show I had a functioning setup and successful restoration.

![k8ssandra_workshop_repair](https://user-images.githubusercontent.com/1249549/117043480-91f71000-ad0d-11eb-9837-332002ec6a71.png)
![k8ssandra_workshop_data](https://user-images.githubusercontent.com/1249549/117043481-928fa680-ad0d-11eb-8305-627aed4c86b5.png)
![k8ssandra_workshop_restore](https://user-images.githubusercontent.com/1249549/117043483-928fa680-ad0d-11eb-9068-1f183d16e591.png)

**Comment by HadesArchitect** [comment]
Here we go! Congrats! https://api.badgr.io/public/assertions/j-I08Qz4S4muPYbqf5-c9w?identity__url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fglenn-sinclair-1b0aa33%2F

**Comment by nordwars** [comment]
Thanks!
