### ISSUE TITLE
[HW] Anirudh Murali

### ISSUE THREAD

**Issue by anihm136** [k8ssandra/workshop#5]
**Name:** Anirudh Murali
**Linkedin Profile:** https://www.linkedin.com/in/anihm136/

Attach the homework screenshots below:
-----------------------------------------
## Exercise 1
![image](https://user-images.githubusercontent.com/49116134/117105242-3d9a7180-ad9b-11eb-930d-a211f1e67722.png)
![image](https://user-images.githubusercontent.com/49116134/117105580-f82a7400-ad9b-11eb-9962-ccabb5a9e524.png)

## Exercise 2
![image](https://user-images.githubusercontent.com/49116134/117105690-2dcf5d00-ad9c-11eb-8053-df0a8ef24fc4.png)
![image](https://user-images.githubusercontent.com/49116134/117105738-4a6b9500-ad9c-11eb-869d-c77c3857d34e.png)

## Exercise 3
![image](https://user-images.githubusercontent.com/49116134/117105832-71c26200-ad9c-11eb-8363-c418bca15fd0.png)

## Exercise 4
![image](https://user-images.githubusercontent.com/49116134/117105967-ad5d2c00-ad9c-11eb-9100-a4114633e8a0.png)
![image](https://user-images.githubusercontent.com/49116134/117106086-e0072480-ad9c-11eb-86af-1a55a251aad7.png)

## Exercise 5
![image](https://user-images.githubusercontent.com/49116134/117106298-3ffdcb00-ad9d-11eb-88a4-de0d421e0d36.png)
![image](https://user-images.githubusercontent.com/49116134/117138800-23778800-adc9-11eb-8ce7-b6d916e40cc5.png)

## Exercise 6
![image](https://user-images.githubusercontent.com/49116134/117140168-ba910f80-adca-11eb-99ed-42404ec6b4c8.png)
![image](https://user-images.githubusercontent.com/49116134/117140319-e4e2cd00-adca-11eb-80a8-6565f8e0a54e.png)

## Exercise 7
![image](https://user-images.githubusercontent.com/49116134/117141439-29229d00-adcc-11eb-8218-0a1fdfdf8d3f.png)
![image](https://user-images.githubusercontent.com/49116134/117141552-4ce5e300-adcc-11eb-950a-ab8ef4d229cc.png)
![image](https://user-images.githubusercontent.com/49116134/117143807-d7c7dd00-adce-11eb-91e9-5c519996a38b.png)

## Exercise 8
![image](https://user-images.githubusercontent.com/49116134/117149796-2aa49300-add5-11eb-85a8-2b9b7627cd03.png)

**Comment by HadesArchitect** [comment]
Congrats! https://api.badgr.io/public/assertions/cY10hUjDS7ujNbKx8uVOMA?identity__url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fanihm136%2F

**Comment by anihm136** [comment]
Thanks! Looking forward to future events
